In [13]:
"""
-----------------------------------------------------------------------------
Assignment-3: Matrix computation exercise using python and numpy
-----------------------------------------------------------------------------
AUTHOR: Soumitra Samanta (soumitra.samanta@gm.rkmvu.ac.in)
-----------------------------------------------------------------------------
Package required:
Numpy: https://numpy.org/
Matplotlib: https://matplotlib.org
-----------------------------------------------------------------------------
"""

import numpy as np
from numpy.random import RandomState
from assignment_3_matrix_computation_exc import *

# for auto-reloading extenrnal modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Please check the file <font color='red'>assignment_3_matrix_computation.py</font> and fillup all the functions implementation from Assignment-2.
-----------------------------------------------------------------------------

# Reduce a non-singular matrix $A$ of order $n$ to $I_n$ by elementary row operations only. Also, find the $A^{-1}$ using the sequence of row operations appplied on $A$. Check your $A^{-1}$ with [numpy.linalg.inv](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html)  with 10 decimal place and also $A^{-1}A=I_n$. Implement your funtion as <font color='red'>reduce_non_sigular_matrix_to_identity</font> started at <font color='red'>line no 643</font> in <font color='red'>assignment_3_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_3_matrix_computation.py</font> within this folder.
[25 points]

In [14]:
# Now test your code
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10
A = []
A=rand_matrix(n,n,l)
print('A random matrices A:\n{}' .format(A))
print('-'*70)

I_A,  INV_A= reduce_non_sigular_matrix_to_identity(A)        
print('The reduced identity form of A:\n{}\nand\nINV_A: \n{} ' .format(np.round(I_A, 3), np.round(INV_A, 3)))
print('-'*70)   

INV_A_np = []# Please uncomment the next line
# print('Check the inverse of A with numpy implementation:\n{}\nand absolute diff|INV_A-INV_A_np| upto {}-th decimal place: \n{}' .format(np.round(INV_A_np, 3), error_decimal, np.round(np.abs(INV_A-INV_A_np), error_decimal)))
print('-'*70)  

I_check = matrix_multiplication(INV_A, A)
print('Check the reduced identity form of A:\n{}' .format(np.round(I_check, 3)))
print('-'*70)   




A random matrices A:
[[7, -5, 7, -6, -1], [8, 4, -5, -4, 6], [8, -1, -3, -9, 6], [8, -2, 6, -9, 9], [8, -1, -1, 4, -5]]
----------------------------------------------------------------------
The reduced identity form of A:
[[ 1.  0.  0.  0.  0.]
 [ 0.  1. -0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
and
INV_A: 
[[ 0.006  0.036 -0.015  0.027  0.072]
 [ 0.251  0.378 -0.272 -0.144 -0.182]
 [ 0.104  0.092 -0.164  0.032 -0.05 ]
 [-0.209 -0.141  0.006  0.156  0.161]
 [-0.228 -0.15   0.069  0.19   0.091]] 
----------------------------------------------------------------------
----------------------------------------------------------------------
Check the reduced identity form of A:
[[ 1.  0. -0. -0.  0.]
 [ 0.  1. -0.  0.  0.]
 [ 0. -0.  1. -0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0. -0. -0. -0.  1.]]
----------------------------------------------------------------------


# Apply the above inverse method to find a soluation of a system $Ax=b$. Where $A$ is non-singular. You have to generate a random system of linear equation ($n$-equations with $n$ unknowns) and check your results. Implement your funtion as <font color='red'>generate_random_linear_system</font> and <font color='red'>soln_n_equations_n_unknowns</font> started at <font color='red'>line no 668 and 703</font> respectively in <font color='red'>assignment_3_matrix_computation.py</font> file in appropriate location. You'll find <font color='red'>assignment_3_matrix_computation.py</font> within this folder.
[25 points]

In [ ]:
# Now test your code
np.random.seed(42)# for reproduce the random numbers
l = 9
n = 5
error_decimal = 10
A = []
A=rand_matrix(n,n,l)
print('A random matrices A:\n{}' .format(A))
print('-'*70)

A, b, x = generate_random_linear_system(n, n)
print('The coefficient matrix A: \n{}' .format(A))
print('-'*70) 
print('Right-hand vector b: \n{}' .format(b))
print('-'*70)
print('Actual soluation x: \n{}' .format(x))
print('-'*70)


x_est, INV_A = soln_n_equations_n_unknowns(A, b) # Please uncomment the next line         
# print('Estimated soluation x_est: \n{}\nand \nabsolute diff|x-x_est| upto {}-th decimal place: \n{}' .format(np.round(x_est, 3), error_decimal, np.round(np.abs(x-x_est), error_decimal)))
print('-'*70)      

#print(matrix_multiplication(A,x_est))




A random matrices A:
[[-7, 9, 2, -9, 0], [-7, 8, 6, 7, 6], [-6, 0, 5, 8, 4], [-6, -7, 5, 8, 2], [-6, 6, 7, 3, 1]]
----------------------------------------------------------------------
The coefficient matrix A: 
[[-4, -7, 4, -2, 2], [-3, -8, 0, -6, 6], [-3, 8, -9, 1, -1], [-3, 6, 4, 2, -6], [-2, 7, 1, -3, -9]]
----------------------------------------------------------------------
Right-hand vector b: 
[[-2, 1, 8, -9, 2], [-2, 8, 0, 5, -4], [-2, 7, -6, 6, -9], [-1, -3, 9, -6, 6], [-1, 7, 5, 1, 3]]
----------------------------------------------------------------------
Actual soluation x: 
[[0.5112781954887219, -0.42515379357484584, -1.0745044429254962, 1.0861244019138774, 0.1982228298017769], [0.030075187969924963, -0.07313738892686306, -0.31989063568010917, 1.956937799043062, 0.04374572795625481], [0.08270676691729344, -0.8147641831852364, 0.8475734791524265, 0.26794258373205804, 1.0293916609706089], [0.05075187969924791, -1.3904647983595346, 0.36927546138072476, -2.089712918660287, 0.2